version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: ./server
    container_name: competeme_server
    depends_on:
      - database
    environment:
      DATABASE_URL: jdbc:postgresql://database:5432/psqlDbName
      DATABASE_USER: psqlUser
      DATABASE_PASSWORD: psqlPassword
    ports:
      - "8080:8080"

  database:
    image: postgres:16
    container_name: psqlDbName
    restart: always
    environment:
      POSTGRES_USER: psqlUser
      POSTGRES_PASSWORD: psqlPassword
      POSTGRES_DB: psqlDbName
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
