/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LeaderboardEntry } from './leaderboard-entry';
// May contain unused imports in some cases
// @ts-ignore
import type { ParticipantResponse } from './participant-response';

/**
 * 
 * @export
 * @interface ChallengeResponse
 */
export interface ChallengeResponse {
    /**
     * 
     * @type {number}
     * @memberof ChallengeResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ChallengeResponse
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChallengeResponse
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof ChallengeResponse
     */
    'goal'?: number;
    /**
     * 
     * @type {string}
     * @memberof ChallengeResponse
     */
    'unit'?: string;
    /**
     * 
     * @type {Array<ParticipantResponse>}
     * @memberof ChallengeResponse
     */
    'participants'?: Array<ParticipantResponse>;
    /**
     * 
     * @type {number}
     * @memberof ChallengeResponse
     */
    'totalProgress'?: number;
    /**
     * 
     * @type {Array<LeaderboardEntry>}
     * @memberof ChallengeResponse
     */
    'leaderboard'?: Array<LeaderboardEntry>;
}

