/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FriendshipKey
 */
export interface FriendshipKey {
    /**
     * 
     * @type {number}
     * @memberof FriendshipKey
     */
    'senderId': number;
    /**
     * 
     * @type {number}
     * @memberof FriendshipKey
     */
    'receiverId': number;
}

