/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RecentActivityResponseDurationUnitsInnerDuration } from './recent-activity-response-duration-units-inner-duration';

/**
 * 
 * @export
 * @interface RecentActivityResponseDurationUnitsInner
 */
export interface RecentActivityResponseDurationUnitsInner {
    /**
     * 
     * @type {boolean}
     * @memberof RecentActivityResponseDurationUnitsInner
     */
    'durationEstimated'?: boolean;
    /**
     * 
     * @type {RecentActivityResponseDurationUnitsInnerDuration}
     * @memberof RecentActivityResponseDurationUnitsInner
     */
    'duration'?: RecentActivityResponseDurationUnitsInnerDuration;
    /**
     * 
     * @type {boolean}
     * @memberof RecentActivityResponseDurationUnitsInner
     */
    'timeBased'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RecentActivityResponseDurationUnitsInner
     */
    'dateBased'?: boolean;
}

