/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RecentActivityResponseDurationUnitsInner } from './recent-activity-response-duration-units-inner';

/**
 * 
 * @export
 * @interface RecentActivityResponseDuration
 */
export interface RecentActivityResponseDuration {
    /**
     * 
     * @type {number}
     * @memberof RecentActivityResponseDuration
     */
    'seconds'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RecentActivityResponseDuration
     */
    'zero'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RecentActivityResponseDuration
     */
    'nano'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RecentActivityResponseDuration
     */
    'negative'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RecentActivityResponseDuration
     */
    'positive'?: boolean;
    /**
     * 
     * @type {Array<RecentActivityResponseDurationUnitsInner>}
     * @memberof RecentActivityResponseDuration
     */
    'units'?: Array<RecentActivityResponseDurationUnitsInner>;
}

