/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RecentActivityResponseDurationUnitsInnerDuration
 */
export interface RecentActivityResponseDurationUnitsInnerDuration {
    /**
     * 
     * @type {number}
     * @memberof RecentActivityResponseDurationUnitsInnerDuration
     */
    'seconds'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RecentActivityResponseDurationUnitsInnerDuration
     */
    'zero'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RecentActivityResponseDurationUnitsInnerDuration
     */
    'nano'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RecentActivityResponseDurationUnitsInnerDuration
     */
    'negative'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RecentActivityResponseDurationUnitsInnerDuration
     */
    'positive'?: boolean;
}

