/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ActivityBreakdown } from './activity-breakdown';
// May contain unused imports in some cases
// @ts-ignore
import type { ActivityStat } from './activity-stat';
// May contain unused imports in some cases
// @ts-ignore
import type { MonthlyStat } from './monthly-stat';
// May contain unused imports in some cases
// @ts-ignore
import type { MostActiveDay } from './most-active-day';
// May contain unused imports in some cases
// @ts-ignore
import type { WeeklyStat } from './weekly-stat';

/**
 * 
 * @export
 * @interface StatsResponse
 */
export interface StatsResponse {
    /**
     * 
     * @type {string}
     * @memberof StatsResponse
     */
    'totalTimeThisWeek': string;
    /**
     * 
     * @type {string}
     * @memberof StatsResponse
     */
    'currentStreak': string;
    /**
     * 
     * @type {string}
     * @memberof StatsResponse
     */
    'longestStreak': string;
    /**
     * 
     * @type {MostActiveDay}
     * @memberof StatsResponse
     */
    'mostActiveDay': MostActiveDay;
    /**
     * 
     * @type {string}
     * @memberof StatsResponse
     */
    'timeLoggedToday': string;
    /**
     * 
     * @type {string}
     * @memberof StatsResponse
     */
    'totalTimeLogged': string;
    /**
     * 
     * @type {ActivityStat}
     * @memberof StatsResponse
     */
    'mostFrequentActivity': ActivityStat;
    /**
     * 
     * @type {ActivityStat}
     * @memberof StatsResponse
     */
    'topActivity': ActivityStat;
    /**
     * 
     * @type {Array<ActivityBreakdown>}
     * @memberof StatsResponse
     */
    'activityBreakdown': Array<ActivityBreakdown>;
    /**
     * 
     * @type {Array<WeeklyStat>}
     * @memberof StatsResponse
     */
    'weeklyStats': Array<WeeklyStat>;
    /**
     * 
     * @type {Array<MonthlyStat>}
     * @memberof StatsResponse
     */
    'monthlyStats': Array<MonthlyStat>;
    /**
     * 
     * @type {string}
     * @memberof StatsResponse
     */
    'totalTimeLastWeek': string;
}

