/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ActivityBreakdown } from './activity-breakdown';

/**
 * 
 * @export
 * @interface StatsResponse
 */
export interface StatsResponse {
    /**
     * 
     * @type {string}
     * @memberof StatsResponse
     */
    'totalTimeThisWeek': string;
    /**
     * 
     * @type {string}
     * @memberof StatsResponse
     */
    'currentStreak': string;
    /**
     * 
     * @type {string}
     * @memberof StatsResponse
     */
    'longestStreak': string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof StatsResponse
     */
    'mostActiveDay': { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof StatsResponse
     */
    'timeLoggedToday': string;
    /**
     * 
     * @type {string}
     * @memberof StatsResponse
     */
    'totalTimeLogged': string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof StatsResponse
     */
    'mostFrequentActivity': { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof StatsResponse
     */
    'topActivity': { [key: string]: string; };
    /**
     * 
     * @type {Array<ActivityBreakdown>}
     * @memberof StatsResponse
     */
    'activityBreakdown': Array<ActivityBreakdown>;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof StatsResponse
     */
    'weeklyStats': { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof StatsResponse
     */
    'monthlyStats': { [key: string]: number; };
    /**
     * 
     * @type {string}
     * @memberof StatsResponse
     */
    'totalTimeLastWeek': string;
}

