/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserSearchResponse
 */
export interface UserSearchResponse {
    /**
     * 
     * @type {}
     * @memberof UserSearchResponse
     */
    'id': ;
    /**
     * 
     * @type {string}
     * @memberof UserSearchResponse
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof UserSearchResponse
     */
    'imageUrl': string;
}

