/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserProfileResponse
 */
export interface UserProfileResponse {
    /**
     * 
     * @type {number}
     * @memberof UserProfileResponse
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponse
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponse
     */
    'imageUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponse
     */
    'dateJoined': string;
}

