import {
  Beer,
  BookOpenText,
  BriefcaseBusiness,
  Brush,
  Calendar,
  Camera,
  CarFront,
  ChefHat,
  Cigarette,
  Clapperboard,
  Clock,
  Code,
  Coffee,
  Dumbbell,
  Gamepad2,
  Heart,
  Music,
  PartyPopper,
  Pen,
  Phone,
  Pizza,
  Plane,
  ShoppingBag,
  Star,
  Users,
} from "lucide-react";
import { ActivityRequestTypeEnum } from "@/api/models/activity-request";

export const icons = [
  { icon: Beer, type: ActivityRequestTypeEnum.Beer },
  { icon: BookOpenText, type: ActivityRequestTypeEnum.Book },
  { icon: BriefcaseBusiness, type: ActivityRequestTypeEnum.Briefcase },
  { icon: Brush, type: ActivityRequestTypeEnum.Brush },
  { icon: Calendar, type: ActivityRequestTypeEnum.Calendar },
  { icon: Camera, type: ActivityRequestTypeEnum.Camera },
  { icon: CarFront, type: ActivityRequestTypeEnum.Car },
  { icon: ChefHat, type: ActivityRequestTypeEnum.ChefHat },
  { icon: Cigarette, type: ActivityRequestTypeEnum.Cigarette },
  { icon: Clapperboard, type: ActivityRequestTypeEnum.Clapperboard },
  { icon: Clock, type: ActivityRequestTypeEnum.Clock },
  { icon: Code, type: ActivityRequestTypeEnum.Code },
  { icon: Coffee, type: ActivityRequestTypeEnum.Coffee },
  { icon: Dumbbell, type: ActivityRequestTypeEnum.Dumbbell },
  { icon: Gamepad2, type: ActivityRequestTypeEnum.Gamepad },
  { icon: Heart, type: ActivityRequestTypeEnum.Heart },
  { icon: Music, type: ActivityRequestTypeEnum.Music },
  { icon: PartyPopper, type: ActivityRequestTypeEnum.Party },
  { icon: Pen, type: ActivityRequestTypeEnum.Pen },
  { icon: Phone, type: ActivityRequestTypeEnum.Phone },
  { icon: Pizza, type: ActivityRequestTypeEnum.Pizza },
  { icon: Plane, type: ActivityRequestTypeEnum.Plane },
  { icon: ShoppingBag, type: ActivityRequestTypeEnum.Shopping },
  { icon: Star, type: ActivityRequestTypeEnum.Star },
  { icon: Users, type: ActivityRequestTypeEnum.Users },
];
