/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Friendship } from '../models';
// @ts-ignore
import type { FriendshipRequest } from '../models';
/**
 * FriendshipManagementApi - axios parameter creator
 * @export
 */
export const FriendshipManagementApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Accepts a pending friend request from another user
         * @summary Accept friend request
         * @param {number} userId 
         * @param {FriendshipRequest} friendshipRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        acceptFriendRequest: async (userId: number, friendshipRequest: FriendshipRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('acceptFriendRequest', 'userId', userId)
            // verify required parameter 'friendshipRequest' is not null or undefined
            assertParamExists('acceptFriendRequest', 'friendshipRequest', friendshipRequest)
            const localVarPath = `/api/v1/users/{userId}/friends/accept`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(friendshipRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Cancels a previously sent friend request
         * @summary Cancel friend request
         * @param {number} userId 
         * @param {FriendshipRequest} friendshipRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelFriendRequest: async (userId: number, friendshipRequest: FriendshipRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('cancelFriendRequest', 'userId', userId)
            // verify required parameter 'friendshipRequest' is not null or undefined
            assertParamExists('cancelFriendRequest', 'friendshipRequest', friendshipRequest)
            const localVarPath = `/api/v1/users/{userId}/friends/cancel`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(friendshipRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves list of user IDs who sent friend requests to the current user
         * @summary Get pending friend requests
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFriendRequests: async (userId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getFriendRequests', 'userId', userId)
            const localVarPath = `/api/v1/users/{userId}/friends/request`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves list of user IDs who are friends with the current user
         * @summary Get friends list
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFriends: async (userId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getFriends', 'userId', userId)
            const localVarPath = `/api/v1/users/{userId}/friends/`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves list of user IDs to whom the current user sent friend requests
         * @summary Get sent friend requests
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSentFriendRequests: async (userId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getSentFriendRequests', 'userId', userId)
            const localVarPath = `/api/v1/users/{userId}/friends/sent`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves friendship statuses between current user and multiple other users
         * @summary Get friendship statuses
         * @param {number} userId 
         * @param {Array<FriendshipRequest>} receiverIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatuses: async (userId: number, receiverIds: Array<FriendshipRequest>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getStatuses', 'userId', userId)
            // verify required parameter 'receiverIds' is not null or undefined
            assertParamExists('getStatuses', 'receiverIds', receiverIds)
            const localVarPath = `/api/v1/users/{userId}/friends/statuses`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (receiverIds) {
                localVarQueryParameter['receiverIds'] = receiverIds;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Checks if there\'s a pending friend request between users
         * @summary Check pending request
         * @param {number} userId 
         * @param {number} receiverId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hasPendingRequest: async (userId: number, receiverId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('hasPendingRequest', 'userId', userId)
            // verify required parameter 'receiverId' is not null or undefined
            assertParamExists('hasPendingRequest', 'receiverId', receiverId)
            const localVarPath = `/api/v1/users/{userId}/friends/pending/{receiverId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)))
                .replace(`{${"receiverId"}}`, encodeURIComponent(String(receiverId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Checks if the current user is friends with another user
         * @summary Check friendship status
         * @param {number} userId 
         * @param {number} receiverId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        isFriend: async (userId: number, receiverId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('isFriend', 'userId', userId)
            // verify required parameter 'receiverId' is not null or undefined
            assertParamExists('isFriend', 'receiverId', receiverId)
            const localVarPath = `/api/v1/users/{userId}/friends/status/{receiverId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)))
                .replace(`{${"receiverId"}}`, encodeURIComponent(String(receiverId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Removes a friend from the user\'s friend list
         * @summary Remove friend
         * @param {number} userId 
         * @param {FriendshipRequest} friendshipRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeFriend: async (userId: number, friendshipRequest: FriendshipRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('removeFriend', 'userId', userId)
            // verify required parameter 'friendshipRequest' is not null or undefined
            assertParamExists('removeFriend', 'friendshipRequest', friendshipRequest)
            const localVarPath = `/api/v1/users/{userId}/friends/remove`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(friendshipRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Sends a friend request to another user
         * @summary Send friend request
         * @param {number} userId 
         * @param {FriendshipRequest} friendshipRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendFriendRequest: async (userId: number, friendshipRequest: FriendshipRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('sendFriendRequest', 'userId', userId)
            // verify required parameter 'friendshipRequest' is not null or undefined
            assertParamExists('sendFriendRequest', 'friendshipRequest', friendshipRequest)
            const localVarPath = `/api/v1/users/{userId}/friends/sendRequest`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(friendshipRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FriendshipManagementApi - functional programming interface
 * @export
 */
export const FriendshipManagementApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FriendshipManagementApiAxiosParamCreator(configuration)
    return {
        /**
         * Accepts a pending friend request from another user
         * @summary Accept friend request
         * @param {number} userId 
         * @param {FriendshipRequest} friendshipRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async acceptFriendRequest(userId: number, friendshipRequest: FriendshipRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.acceptFriendRequest(userId, friendshipRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FriendshipManagementApi.acceptFriendRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Cancels a previously sent friend request
         * @summary Cancel friend request
         * @param {number} userId 
         * @param {FriendshipRequest} friendshipRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelFriendRequest(userId: number, friendshipRequest: FriendshipRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelFriendRequest(userId, friendshipRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FriendshipManagementApi.cancelFriendRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves list of user IDs who sent friend requests to the current user
         * @summary Get pending friend requests
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFriendRequests(userId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<number>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFriendRequests(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FriendshipManagementApi.getFriendRequests']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves list of user IDs who are friends with the current user
         * @summary Get friends list
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFriends(userId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<number>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFriends(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FriendshipManagementApi.getFriends']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves list of user IDs to whom the current user sent friend requests
         * @summary Get sent friend requests
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSentFriendRequests(userId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<number>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSentFriendRequests(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FriendshipManagementApi.getSentFriendRequests']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves friendship statuses between current user and multiple other users
         * @summary Get friendship statuses
         * @param {number} userId 
         * @param {Array<FriendshipRequest>} receiverIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStatuses(userId: number, receiverIds: Array<FriendshipRequest>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Friendship>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStatuses(userId, receiverIds, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FriendshipManagementApi.getStatuses']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Checks if there\'s a pending friend request between users
         * @summary Check pending request
         * @param {number} userId 
         * @param {number} receiverId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hasPendingRequest(userId: number, receiverId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hasPendingRequest(userId, receiverId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FriendshipManagementApi.hasPendingRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Checks if the current user is friends with another user
         * @summary Check friendship status
         * @param {number} userId 
         * @param {number} receiverId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async isFriend(userId: number, receiverId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.isFriend(userId, receiverId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FriendshipManagementApi.isFriend']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Removes a friend from the user\'s friend list
         * @summary Remove friend
         * @param {number} userId 
         * @param {FriendshipRequest} friendshipRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeFriend(userId: number, friendshipRequest: FriendshipRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeFriend(userId, friendshipRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FriendshipManagementApi.removeFriend']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Sends a friend request to another user
         * @summary Send friend request
         * @param {number} userId 
         * @param {FriendshipRequest} friendshipRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendFriendRequest(userId: number, friendshipRequest: FriendshipRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendFriendRequest(userId, friendshipRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FriendshipManagementApi.sendFriendRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FriendshipManagementApi - factory interface
 * @export
 */
export const FriendshipManagementApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FriendshipManagementApiFp(configuration)
    return {
        /**
         * Accepts a pending friend request from another user
         * @summary Accept friend request
         * @param {number} userId 
         * @param {FriendshipRequest} friendshipRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        acceptFriendRequest(userId: number, friendshipRequest: FriendshipRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.acceptFriendRequest(userId, friendshipRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Cancels a previously sent friend request
         * @summary Cancel friend request
         * @param {number} userId 
         * @param {FriendshipRequest} friendshipRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelFriendRequest(userId: number, friendshipRequest: FriendshipRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cancelFriendRequest(userId, friendshipRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves list of user IDs who sent friend requests to the current user
         * @summary Get pending friend requests
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFriendRequests(userId: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<number>> {
            return localVarFp.getFriendRequests(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves list of user IDs who are friends with the current user
         * @summary Get friends list
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFriends(userId: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<number>> {
            return localVarFp.getFriends(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves list of user IDs to whom the current user sent friend requests
         * @summary Get sent friend requests
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSentFriendRequests(userId: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<number>> {
            return localVarFp.getSentFriendRequests(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves friendship statuses between current user and multiple other users
         * @summary Get friendship statuses
         * @param {number} userId 
         * @param {Array<FriendshipRequest>} receiverIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatuses(userId: number, receiverIds: Array<FriendshipRequest>, options?: RawAxiosRequestConfig): AxiosPromise<Array<Friendship>> {
            return localVarFp.getStatuses(userId, receiverIds, options).then((request) => request(axios, basePath));
        },
        /**
         * Checks if there\'s a pending friend request between users
         * @summary Check pending request
         * @param {number} userId 
         * @param {number} receiverId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hasPendingRequest(userId: number, receiverId: number, options?: RawAxiosRequestConfig): AxiosPromise<boolean> {
            return localVarFp.hasPendingRequest(userId, receiverId, options).then((request) => request(axios, basePath));
        },
        /**
         * Checks if the current user is friends with another user
         * @summary Check friendship status
         * @param {number} userId 
         * @param {number} receiverId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        isFriend(userId: number, receiverId: number, options?: RawAxiosRequestConfig): AxiosPromise<boolean> {
            return localVarFp.isFriend(userId, receiverId, options).then((request) => request(axios, basePath));
        },
        /**
         * Removes a friend from the user\'s friend list
         * @summary Remove friend
         * @param {number} userId 
         * @param {FriendshipRequest} friendshipRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeFriend(userId: number, friendshipRequest: FriendshipRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeFriend(userId, friendshipRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Sends a friend request to another user
         * @summary Send friend request
         * @param {number} userId 
         * @param {FriendshipRequest} friendshipRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendFriendRequest(userId: number, friendshipRequest: FriendshipRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.sendFriendRequest(userId, friendshipRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FriendshipManagementApi - object-oriented interface
 * @export
 * @class FriendshipManagementApi
 * @extends {BaseAPI}
 */
export class FriendshipManagementApi extends BaseAPI {
    /**
     * Accepts a pending friend request from another user
     * @summary Accept friend request
     * @param {number} userId 
     * @param {FriendshipRequest} friendshipRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FriendshipManagementApi
     */
    public acceptFriendRequest(userId: number, friendshipRequest: FriendshipRequest, options?: RawAxiosRequestConfig) {
        return FriendshipManagementApiFp(this.configuration).acceptFriendRequest(userId, friendshipRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Cancels a previously sent friend request
     * @summary Cancel friend request
     * @param {number} userId 
     * @param {FriendshipRequest} friendshipRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FriendshipManagementApi
     */
    public cancelFriendRequest(userId: number, friendshipRequest: FriendshipRequest, options?: RawAxiosRequestConfig) {
        return FriendshipManagementApiFp(this.configuration).cancelFriendRequest(userId, friendshipRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves list of user IDs who sent friend requests to the current user
     * @summary Get pending friend requests
     * @param {number} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FriendshipManagementApi
     */
    public getFriendRequests(userId: number, options?: RawAxiosRequestConfig) {
        return FriendshipManagementApiFp(this.configuration).getFriendRequests(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves list of user IDs who are friends with the current user
     * @summary Get friends list
     * @param {number} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FriendshipManagementApi
     */
    public getFriends(userId: number, options?: RawAxiosRequestConfig) {
        return FriendshipManagementApiFp(this.configuration).getFriends(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves list of user IDs to whom the current user sent friend requests
     * @summary Get sent friend requests
     * @param {number} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FriendshipManagementApi
     */
    public getSentFriendRequests(userId: number, options?: RawAxiosRequestConfig) {
        return FriendshipManagementApiFp(this.configuration).getSentFriendRequests(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves friendship statuses between current user and multiple other users
     * @summary Get friendship statuses
     * @param {number} userId 
     * @param {Array<FriendshipRequest>} receiverIds 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FriendshipManagementApi
     */
    public getStatuses(userId: number, receiverIds: Array<FriendshipRequest>, options?: RawAxiosRequestConfig) {
        return FriendshipManagementApiFp(this.configuration).getStatuses(userId, receiverIds, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Checks if there\'s a pending friend request between users
     * @summary Check pending request
     * @param {number} userId 
     * @param {number} receiverId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FriendshipManagementApi
     */
    public hasPendingRequest(userId: number, receiverId: number, options?: RawAxiosRequestConfig) {
        return FriendshipManagementApiFp(this.configuration).hasPendingRequest(userId, receiverId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Checks if the current user is friends with another user
     * @summary Check friendship status
     * @param {number} userId 
     * @param {number} receiverId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FriendshipManagementApi
     */
    public isFriend(userId: number, receiverId: number, options?: RawAxiosRequestConfig) {
        return FriendshipManagementApiFp(this.configuration).isFriend(userId, receiverId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Removes a friend from the user\'s friend list
     * @summary Remove friend
     * @param {number} userId 
     * @param {FriendshipRequest} friendshipRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FriendshipManagementApi
     */
    public removeFriend(userId: number, friendshipRequest: FriendshipRequest, options?: RawAxiosRequestConfig) {
        return FriendshipManagementApiFp(this.configuration).removeFriend(userId, friendshipRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Sends a friend request to another user
     * @summary Send friend request
     * @param {number} userId 
     * @param {FriendshipRequest} friendshipRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FriendshipManagementApi
     */
    public sendFriendRequest(userId: number, friendshipRequest: FriendshipRequest, options?: RawAxiosRequestConfig) {
        return FriendshipManagementApiFp(this.configuration).sendFriendRequest(userId, friendshipRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

