/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { StatsResponse } from '../models';
/**
 * UserStatisticsApi - axios parameter creator
 * @export
 */
export const UserStatisticsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves statistics and analytics for the specified user
         * @summary Get user statistics
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStats: async (userId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getStats', 'userId', userId)
            const localVarPath = `/api/v1/users/{userId}/stats/`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserStatisticsApi - functional programming interface
 * @export
 */
export const UserStatisticsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserStatisticsApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves statistics and analytics for the specified user
         * @summary Get user statistics
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStats(userId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StatsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStats(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserStatisticsApi.getStats']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserStatisticsApi - factory interface
 * @export
 */
export const UserStatisticsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserStatisticsApiFp(configuration)
    return {
        /**
         * Retrieves statistics and analytics for the specified user
         * @summary Get user statistics
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStats(userId: number, options?: RawAxiosRequestConfig): AxiosPromise<StatsResponse> {
            return localVarFp.getStats(userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserStatisticsApi - object-oriented interface
 * @export
 * @class UserStatisticsApi
 * @extends {BaseAPI}
 */
export class UserStatisticsApi extends BaseAPI {
    /**
     * Retrieves statistics and analytics for the specified user
     * @summary Get user statistics
     * @param {number} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserStatisticsApi
     */
    public getStats(userId: number, options?: RawAxiosRequestConfig) {
        return UserStatisticsApiFp(this.configuration).getStats(userId, options).then((request) => request(this.axios, this.basePath));
    }
}

