/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ActivityRequest
 */
export interface ActivityRequest {
    /**
     * 
     * @type {string}
     * @memberof ActivityRequest
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof ActivityRequest
     */
    'type': ActivityRequestTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ActivityRequest
     */
    'duration': number;
}

export const ActivityRequestTypeEnum = {
    Beer: 'BEER',
    Book: 'BOOK',
    Briefcase: 'BRIEFCASE',
    Brush: 'BRUSH',
    Calendar: 'CALENDAR',
    Camera: 'CAMERA',
    Car: 'CAR',
    ChefHat: 'CHEF_HAT',
    Cigarette: 'CIGARETTE',
    Clapperboard: 'CLAPPERBOARD',
    Clock: 'CLOCK',
    Code: 'CODE',
    Coffee: 'COFFEE',
    Dumbbell: 'DUMBBELL',
    Gamepad: 'GAMEPAD',
    Heart: 'HEART',
    Music: 'MUSIC',
    Party: 'PARTY',
    Pen: 'PEN',
    Phone: 'PHONE',
    Pizza: 'PIZZA',
    Plane: 'PLANE',
    Shopping: 'SHOPPING',
    Star: 'STAR',
    Users: 'USERS'
} as const;

export type ActivityRequestTypeEnum = typeof ActivityRequestTypeEnum[keyof typeof ActivityRequestTypeEnum];


