/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FriendshipKey } from './friendship-key';

/**
 * 
 * @export
 * @interface Friendship
 */
export interface Friendship {
    /**
     * 
     * @type {FriendshipKey}
     * @memberof Friendship
     */
    'id': FriendshipKey;
    /**
     * 
     * @type {string}
     * @memberof Friendship
     */
    'status': FriendshipStatusEnum;
}

export const FriendshipStatusEnum = {
    Pending: 'PENDING',
    Accepted: 'ACCEPTED'
} as const;

export type FriendshipStatusEnum = typeof FriendshipStatusEnum[keyof typeof FriendshipStatusEnum];


