/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MostActiveDay
 */
export interface MostActiveDay {
    /**
     * 
     * @type {string}
     * @memberof MostActiveDay
     */
    'dayOfWeek': string;
    /**
     * 
     * @type {string}
     * @memberof MostActiveDay
     */
    'averageDuration': string;
}

