name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Build with system Gradle
        run: gradle build
        working-directory: ./server

      - name: Publish Test Result
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: JUnit Test Results
          path: ./server/build/test-results/test/*.xml
          reporter: java-junit