name: Code quality

on:
  push:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run lint
        run: npm i && npm run lintcheck && npm run typecheck
        working-directory: ./web
